name: Deploy
on:
  push:
    branches: [main]
    
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Install jpackage dependencies
        run: |
          sudo apt update
          sudo apt install -y fakeroot libfuse2

      - name: Create DEB package
        run: |
          jpackage \
            --input target/ \
            --name LSOListGenerator \
            --main-jar LSOListGenerator-1.0.jar \
            --main-class pl.bator.lso_list_generator.LSOListGeneratorApplication \
            --type deb \
            --icon src/main/resources/logo.png \

  
  build-windows:
    needs: [ build-linux ]
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Create EXE package
        run: |
          jpackage ^
            --input target\ ^
            --name LSOListGenerator ^
            --main-jar LSOListGenerator-1.0.jar ^
            --main-class pl.bator.lso_list_generator.LSOListGeneratorApplication ^
            --type exe ^
            --icon src\main\resources\logo.png ^
            --dest .

  release:
    needs: [ build-linux, build-windows ]
    runs-on: ubuntu-latest
    steps:
      - name: Download DEB artifact
        uses: actions/download-artifact@v3
        with:
          name: lso-deb

      - name: Download EXE artifact
        uses: actions/download-artifact@v3
        with:
          name: lso-exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            LSOListGenerator*.deb
            LSOListGenerator*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
