name: Deploy
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Install jpackage dependencies
        run: |
          sudo apt update
          sudo apt install -y fakeroot libfuse2

      - name: Create DEB package
        run: |
          jpackage \
            --input target/ \
            --name LSOListGenerator \
            --main-jar LSOListGenerator-1.0.jar \
            --main-class pl.bator.lso_list_generator.LSOListGeneratorApplication \
            --type deb \
            --icon src/main/resources/logo.png \
            --dest .

      - name: Upload DEB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lso-deb
          path: lsolistgenerator*.deb

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Create EXE package
        run: |
          jpackage --input target\ --name LSOListGenerator --main-jar LSOListGenerator-1.0.jar --main-class pl.bator.lso_list_generator.LSOListGeneratorApplication --type msi --icon src\main\resources\logo.ico --dest . --win-shortcut
        shell: pwsh

      - name: Upload MSI as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lso-msi
          path: LSOListGenerator*.msi

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download DEB artifact
        uses: actions/download-artifact@v4
        with:
          name: lso-deb

      - name: Download MSI artifact
        uses: actions/download-artifact@v4
        with:
          name: lso-msi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          files: |
            lsolistgenerator*.deb
            LSOListGenerator*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
